### ISSUE TITLE
How to generating voxelized models & rendering images from the ShapeNet v1 dataset?

### ISSUE THREAD

**Issue by AlexsaseXie** [chrischoy/3D-R2N2#52]
I only found a preprocessed dataset download link in your repo, but I'm interested in how voxelization and rendering is done from the original ShapeNet v1 dataset. Can you shed light on how these 2 processes are done or are there any code that I can refer to? Thanks

**Comment by YiruS** [comment]
Same question here. Do we need to "fake" camera intrinsic matrix?

**Comment by noamgat** [comment]
I am also very interested in this.

**Comment by LifeBeyondExpectations** [comment]
totally agree, I have no idea about this issue. where can I find it ?

**Comment by AlexsaseXie** [comment]
The author released the rendering script in this [commit](https://github.com/chrischoy/3D-R2N2/commit/3f621154844cca4ecce03da56609ffe98563de9c). After some sort of modification you can use it to render the view images by `blender --python blender_render.py`.(Install blender first)

**Comment by markuspaschi** [comment]
As for rendering images, I modified the script (added some more features). I'll post a link to my repo when im finished.

**Comment by hiyyg** [comment]
@markuspaschi Could you kindly share your rendering script?

**Comment by AlexsaseXie** [comment]
I modified the script and made it work on ShapeNet.v1/
Here are some hints (Working on Ubuntu 16.04):

- If you install blender by `apt install blender`, the blender you got will be 2.76b and should have no numpy. You cannot easily install numpy for the python environment of blender.
- You cannot` import config` even if it's in the same dir. Modify such import into a single blender_render.py instead.
- Use for loop to render 24 views of each model
- Use python.multiprocess or python.thread or blender -t to accelerate the whole process.

Optional: if you want to get the depth map as well, use OpenEXR first (thus blender's output format is OpenEXR) and then tranfer it into pngs you want.

**Comment by zyqz97** [comment]
@AlexsaseXie I have the same problem of the image generating. 
Could you tell me how can I render the different-view image of models? There is something wrong that No module name bpy when I run the python script (blender_renderer.py) directly. Now I can do nothing with the script and feel confused.
Look forward to your reply. Thank you!

**Comment by zyqz97** [comment]
@AlexsaseXie  Could you share the modified script? I have the same problem on image rendering and try a lot. But it doesn't work.

Look forward to your reply. Thank you!!

**Comment by DouYishun** [comment]
Hi @AlexsaseXie ，how did you set the value of "cfg.RENDERING.MAX_CAMERA_DIST" in blender_renderer.py?
And could you please share anything else that need to be modified?

**Comment by AlexsaseXie** [comment]
> Hi @AlexsaseXie ，how did you set the value of "cfg.RENDERING.MAX_CAMERA_DIST" in blender_renderer.py?
> And could you please share anything else that need to be modified?

That value is 1.75.
I got that from [https://github.com/jgwak/McRecon/blob/b90acc3017ba2dbb99ef13bb2033be30059d7108/lib/get_projection.py#L72](url) which tells you have to generate camera matrix from the parameters of 3D-R2N2.

**Comment by DouYishun** [comment]
Thank you very much. @AlexsaseXie

**Comment by markuspaschi** [comment]
I wrote a Master Thesis about 3D-Methods including Pixel2Mesh (in German). But my repository can be found here:
https://github.com/markuspaschi/ShapeNetTools
Go into DataSet_Tools/Renderer to find hints about how I used the blender renderer to create images.
I changed some parameters, its probably not perfect (but it may be a starting point for some people).

**Comment by DreamBlack** [comment]
> I modified the script and made it work on ShapeNet.v1/
> Here are some hints (Working on Ubuntu 16.04):
> 
> * If you install blender by `apt install blender`, the blender you got will be 2.76b and should have no numpy. You cannot easily install numpy for the python environment of blender.
> * You cannot` import config` even if it's in the same dir. Modify such import into a single blender_render.py instead.
> * Use for loop to render 24 views of each model
> * Use python.multiprocess or python.thread or blender -t to accelerate the whole process.
> 
> Optional: if you want to get the depth map as well, use OpenEXR first (thus blender's output format is OpenEXR) and then tranfer it into pngs you want.

Thanks for you sharing.
When i run blender_render.py, i have met some errors,
eg. 
   KeyError: 'bpy_prop_collection[key]: key "Lamp" not found'
   AttributeError: 'BlendData' object has no attribute 'lamps'
I have no ideal about how to deal with these errors.
Have you met such errors?
Thanks a lot.

**Comment by djaniak** [comment]
This may be late but you are probably using a new blender api (2.91) which doesn't support these attributes. You should use version 2.79 of blender and blenderpy, the first one is easy to install but I am struggling but the second one (blenderpy).

**Comment by Wi-sc** [comment]
Hi @AlexsaseXie, have you found how to generate voxelized models? I'm also interested in it.

**Comment by winnechan** [comment]
Hi @AlexsaseXie @markuspaschi , do you know why the colors of the model in rendered images are different in ubuntu and windows though I have set the color_model to RGBA ?

The model in meshlab

![21388cc7-e0d9-4d00-b605-135402d6b534](https://user-images.githubusercontent.com/9052195/180756112-7b0c4390-63a0-48f9-89ec-dba1731f5b9a.jpg)


In Ubuntu (blender 2.79)

![01](https://user-images.githubusercontent.com/9052195/180755659-2535db11-979a-4e47-a1fa-ffa214ce3033.png)

In Windows (blender 2.79)

![02](https://user-images.githubusercontent.com/9052195/180756782-937980ea-25bd-403e-9069-e06fe12ed46a.png)

**Comment by Michaelwjh** [comment]
> > I modified the script and made it work on ShapeNet.v1/
> > Here are some hints (Working on Ubuntu 16.04):
> > 
> > * If you install blender by `apt install blender`, the blender you got will be 2.76b and should have no numpy. You cannot easily install numpy for the python environment of blender.
> > * You cannot` import config` even if it's in the same dir. Modify such import into a single blender_render.py instead.
> > * Use for loop to render 24 views of each model
> > * Use python.multiprocess or python.thread or blender -t to accelerate the whole process.
> > 
> > Optional: if you want to get the depth map as well, use OpenEXR first (thus blender's output format is OpenEXR) and then tranfer it into pngs you want.
> 
> Thanks for you sharing. When i run blender_render.py, i have met some errors, eg. KeyError: 'bpy_prop_collection[key]: key "Lamp" not found' AttributeError: 'BlendData' object has no attribute 'lamps' I have no ideal about how to deal with these errors. Have you met such errors? Thanks a lot.

have you solved these problems? Could you share the methods?

**Comment by Michaelwjh** [comment]
> This may be late but you are probably using a new blender api (2.91) which doesn't support these attributes. You should use version 2.79 of blender and blenderpy, the first one is easy to install but I am struggling with the second one (blenderpy).

Could you tell me how to download blenderpy2.79?
