### ISSUE TITLE
After activating env, runing demo.py cause "Problem occurred during compilation"

### ISSUE THREAD

**Issue by liujiaxing** [chrischoy/3D-R2N2#2]
Hi, i was trying to reproduce the experiment, and i follow the given instructions,  however, i will get an environment with python 3.4 where the code complain syntax error. I try to explicitly define a python 3.5 environment, however, more errors comes, listed as following, could any one help me? Thanks!

Problem occurred during compilation with the command line below:
```
- /usr/bin/g++ -shared -g -march=core-avx2 -mcx16 -msahf -mmovbe -maes -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mno-rtm -mno-hle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=15360 -mtune=generic -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/numpy/core/include -I/root/.pyenv/versions/3.5.1/include/python3.5m -I/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/theano/gof -fvisibility=hidden -o /root/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.1-64/lazylinker_ext/lazylinker_ext.so /root/.theano/compiledir_Linux-4.4--generic-x86_64-with-debian-jessie-sid-x86_64-3.5.1-64/lazylinker_ext/mod.cpp -L/root/.pyenv/versions/3.5.1/lib -lpython3.5m
- /usr/bin/ld: /root/.pyenv/versions/3.5.1/lib/libpython3.5m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC
- /root/.pyenv/versions/3.5.1/lib/libpython3.5m.a: error adding symbols: Bad value
- collect2: error: ld returned 1 exit status
- 
- Traceback (most recent call last):
-   File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/theano/gof/lazylinker_c.py", line 74, in <module>
-     raise ImportError()
- ImportError
- 
- During handling of the above exception, another exception occurred:
- 
- Traceback (most recent call last):
-   File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/theano/gof/lazylinker_c.py", line 91, in <module>
-     raise ImportError()
- ImportError
- 
- During handling of the above exception, another exception occurred:
- 
- Traceback (most recent call last):
-   File "demo.py", line 17, in <module>
-     from models import load_model
-   File "/home/yht/yang3d/hope/3D-R2N2/models/__init__.py", line 1, in <module>
-     from models.gru_net import GRUNet
-   File "/home/yht/yang3d/hope/3D-R2N2/models/gru_net.py", line 4, in <module>
-     import theano
-   File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/theano/__init__.py", line 63, in <module>
-     from theano.compile import (
-   File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/theano/compile/__init__.py", line 9, in <module>
-     from theano.compile.function_module import *
-   File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/theano/compile/function_module.py", line 22, in <module>
-     import theano.compile.mode
-   File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/theano/compile/mode.py", line 12, in <module>
-     import theano.gof.vm
-   File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/theano/gof/vm.py", line 638, in <module>
-     from . import lazylinker_c
-   File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/theano/gof/lazylinker_c.py", line 126, in <module>
-     preargs=args)
-   File "/root/.pyenv/versions/3.5.1/lib/python3.5/site-packages/theano/gof/cmodule.py", line 2204, in compile_str
-     (status, compile_stderr.replace('\n', '. ')))
- Exception: Compilation failed (return status=1): /usr/bin/ld: /root/.pyenv/versions/3.5.1/lib/libpython3.5m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC. /root/.pyenv/versions/3.5.1/lib/libpython3.5m.a: error adding symbols: Bad value. collect2: error: ld returned 1 exit status. 
```

**Comment by jgwak** [comment]
It looks like you are using the almost latest version of python. Have you compiled it yourself? If so, try recompiling it with `--enable-shared ` option. If you used some package manager to install this python, it is highly likely that there exists developer package, like `python-dev` in Debian-based APT's, that you can install out-of-box.

**Comment by liujiaxing** [comment]
Hi, thank you @jgwak .
In fact i am using pyenv manage python enviroment, and python 3.5.1 is set globally default. I do this because before set python 3.5 as global, 2.7 is default. With 2.7 as default, following instructions will have python 3.4 as virtual environment, and run demo.py will receive syntax error saying that the star expression in line 20 of solver.py is only supported from python 3.5.
Should i uninstall pyenv and  install python 3.5 on host from compiling?  or reinstall python 2.7?

**Comment by jgwak** [comment]
We developed on the latest version of python and did not work on backward compatibility. I'm sorry I can only guarantee that the code works on version 3.5.1 and above. I found an easy fix for your problem. Please check the link to the documentation below.

https://github.com/yyuu/pyenv/tree/master/plugins/python-build#building-with---enable-shared

**Comment by jgwak** [comment]
> demo.py will receive syntax error saying that the star expression in line 20 of solver.py is only supported from python 3.5.

By the way, I cannot find any asterisk at [lib/solver.py line 20](https://github.com/chrischoy/3D-R2N2/blob/master/lib/solver.py#L20). Are you on the latest version of our code?

**Comment by liujiaxing** [comment]
I am so sorry for my typing mistake,  the referred star expression was at lib/solver.py line 218. 
Sorry for this.

> We developed on the latest version of python and did not work on backward compatibility. I'm sorry I can only guarantee that the code works on version 3.5.1 and above. I found an easy fix for your problem. Please check the link to the documentation below. `We developed on the latest version of python and did not work on backward compatibility.

Did you developed on a virtual environment with the latest version of python or on system with the latest version of python installed?

On my ubuntu 14.04 with python 2.7.9 as default,  the instruction `virtualenv -p python3 --system-site-packages py3`  will only create a environment with python 3.4, which is not compatible with the code, any advise?

**Comment by jgwak** [comment]
Thanks for the feedback. I developed on python 3.5.1 I compiled myself in virtualenv. Again, since you said the you are using pyenv, official documentation from pyenv gives you an option to build latest python with `--enable-shared` option. Please check refer to this documentation.

https://github.com/yyuu/pyenv/tree/master/plugins/python-build#building-with---enable-shared

**Comment by liujiaxing** [comment]
Hi, @jgwak  
Thanks for your help, now things work much better.

I have tested on both docker and my host, and find that if python version is lower than 2.7.9, 
`virtualenv -p python3 --system-site-packages py3` would only create python environment version 3.4, which is not sufficient for this code.

**Comment by jgwak** [comment]
Glad it helped. That's a strange behavior but since this is not an issue related to our project and I will close this issue.
